نام: ? CI

؟؟؟؟:
  ?? ??:
    ?? ??: [ "?? "؟?? ?? "("The")"را")"؟؟؟؟")"؟؟؟؟")"؟؟؟؟")"؟؟؟؟")"؟؟؟؟")"؟؟؟؟")"؟؟؟؟"("The")"؟؟؟؟")""("The")"را")"؟؟؟؟")"؟؟؟؟")"؟؟؟؟")"؟؟؟؟")"("""""""""""""""""""""""?؟" "("؟؟؟؟")"[]؟؟؟؟ ")"؟؟؟؟ "[]""?? """""؟؟؟؟ ؟؟ ؟؟ ؟؟ ؟؟ ؟؟ ؟؟ ؟؟ ؟؟ ؟؟ ؟؟ ؟؟ ؟؟ ؟؟ ؟؟ ؟؟ ؟؟ ؟؟؟؟ ")"؟؟؟؟ ]
  pull_requestpull_requestpull_requestpull_requestpull_requestpull_requestpull_requestpull_requestpull_requestpull_requestpull_requestpull_requestpull_requestpull_requestpull_requestpull_requestpull_requestpull_requestpull_requestpull_requestpull_requestpull_requestpull_requestpull_requestpull_requestpull_requestpull_requestpull_requestpull_requestpull_requestpull_requestpull_request:
    ?? ??: [ ?? .؟؟؟؟ "?? .""?? ."")"؟؟؟؟ ؟؟؟؟ "?? "]"؟؟؟؟""مشکل." """""""""""[]" ؟؟؟؟ ?? ." []"The")"را")"("""""?? .""""")"""""?? """""؟؟؟؟ "?? " ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ")"؟؟؟؟ ]

?? ??:
  ?? ??:

    ?? ??: ?? ??
    ؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟:
      ?? ?? ?? ?? ? ??: 4
      ؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟:
        ?? ??: 3.73.7?? 3.83.8 ?? 3.93.9]

    ؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟:
    - ?? ?? ?? ?? ??: ?? checkout@v4
    - ؟؟؟؟: ?? 2 ?? 2 ?? 2 تا؟؟ 2 تا؟؟ }
      ?? ?? ?? ?? ??: ?? setup-python@v3
      ?? ??:
        ?? ??: $؟؟؟؟؟ ؟؟؟؟ $ ?? ?? }
    - ?? ?? ???? ??????
      ?? ??: |
        ?? ؟؟؟؟ ?? ?? ?? ?? ?? ?? ؟؟؟؟ ؟؟؟؟ ؟؟؟؟ ؟؟؟؟ ?? ?? ?? ?? ??? ?? ???" ?? ؟؟ ؟؟ ؟؟ - ???? - ???? - ??? -??? -??? -??? -??? -??? -??? -???? -??? -??? -???? -????? -?????? -?????? -?????? -?????? -?????? - ????? - ????? - ????? - ????? - ????? - ????? - ????? - ????? - ????? - ????? - ????? - ?????? - ?????? - ??????? - ???????? - ???????? - ????????? - ?????? - ???????  ?? ـ؟ ـ ؟ ـ ؟ ـ ؟ ـ؟ ـ؟ ـ؟؟ ـ؟؟ ـ ؟؟ ـ ??? ـ ??? ؟ ـ ?? ? - ?? ?? - ??? - ???? - ???? - ?????????  ?? - ?? - ?? - ??? -???? - ?? ?  ?? -؟؟؟؟؟؟ - ??  ?? - ?????? -؟؟؟؟؟؟؟؟؟
        ?? ?? ? -؟؟؟؟؟ install-r requirements.txt?? ?? .txt ?? install-r requirements.txtirements.txt?? install-r requirements.txt?? سوالات.txt؟؟ install-r requirements.txt ?? .txt?? install-r requirements.txt?? سوالات.txt؟؟ install-r requirements.txtirements.txt?? install-r requirements.txt ?? quirements.txt ? install-r requirements.txt.txt? install-r requirements.txt?? سوالات.txt؟؟ install-r requirements.txtirements.txt?? install-r requirements.txt ?? quirements.txt ? install-r requirements.txtوالات.txt?? install-r requirements.txt ?? quirements.txt ? install-r requirements.txtirements.txt?? install-r requirements.txtهquirements.txt پیپ install-r requirements.txt
    - ؟؟؟؟: ?? ?? ?? ??
      ?? ??: |
        ?? ?? Python.py
